FROM openjdk:8-jdk-alpine
MAINTAINER Mageshwaran <mageshwaran.k.s@cognizant.com>
ADD target/greenstarapp-student-service.jar greenstarapp-student-service.jar
ENTRYPOINT ["java", "-jar", "/greenstarapp-student-service.jar"]
EXPOSE 2630