FROM openjdk:8-jdk-alpine
MAINTAINER Mageshwaran <mageshwaran.k.s@cognizant.com>
ADD target/greenstarapp-perfdata-service.jar greenstarapp-perfdata-service.jar
ENTRYPOINT ["java", "-jar", "/greenstarapp-perfdata-service.jar"]
EXPOSE 2640