info:
  component: Edge Server
  
management:
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true


zuul:
  ribbon:
    eager-load:
      enabled: true
  prefix: /api
  routes:
    security: 
      path: /security/login
      serviceId: security-service
    admin:
      path: /admin/**
      serviceId: security-service
    school: 
      path: /school/**
      serviceId: school-service
    perfdata: 
      path: /perfdata/**
      serviceId: perfdata-service
  host:
    connect-timeout-millis: 60000 
    socket-timeout-millis: 60000
    connection-request-timeout-millis: 60000

hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 60000
ribbon: 
  ReadTimeout: 60000
  connection-timeout: 60000


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
    org.springframework.security: ERROR
    com.cognizant.outreach: INFO
  pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: gateway-server.log
  
greenapp.security.jwt.secret: greenappsecret