FROM openjdk:8-jdk-alpine
MAINTAINER Mageshwaran <mageshwaran.k.s@cognizant.com>
ADD target/greenstarapp-security-service.jar greenstarapp-security-service.jar
ENTRYPOINT ["java", "-jar", "/greenstarapp-security-service.jar"]
EXPOSE 2610