FROM openjdk:8-jdk-alpine
MAINTAINER Mageshwaran <mageshwaran.k.s@cognizant.com>
ADD target/greenstarapp-testutil.jar greenstarapp-testutil.jar
ENTRYPOINT ["java", "-jar", "/greenstarapp-testutil.jar"]
EXPOSE 8766