server:  
  port: ${PORT:2690}

spring:  
  application:
    name: school-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/greenstar?useSSL=false
    username: dbuser
    password: dbuser123
  
#  jpa:
#    show-sql: true
logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: testutil-application.log
    level:
      org.springframework: WARN
      org.hibernate: WARN
      com.cognizant.outreach: INFO
   #   org.hibernate.SQL: debug
   #   org.hibernate.type.descriptor.sql: trace