/*
-- Query: SELECT * FROM greenstar.india_state_district
LIMIT 0, 1000

-- Date: 2019-03-17 10:50
*/
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (2,'ANDAMAN AND NICOBAR ISLANDS','NICOBARS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (3,'ANDAMAN AND NICOBAR ISLANDS','NORTH AND MIDDLE ANDAMAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (4,'ANDAMAN AND NICOBAR ISLANDS','SOUTH ANDAMANS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (5,'ANDHRA PRADESH','ANANTAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (6,'ANDHRA PRADESH','CHITTOOR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (7,'ANDHRA PRADESH','EAST GODAVARI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (8,'ANDHRA PRADESH','GUNTUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (9,'ANDHRA PRADESH','KRISHNA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (10,'ANDHRA PRADESH','KURNOOL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (11,'ANDHRA PRADESH','PRAKASAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (12,'ANDHRA PRADESH','SPSR NELLORE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (13,'ANDHRA PRADESH','SRIKAKULAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (14,'ANDHRA PRADESH','VISAKHAPATANAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (15,'ANDHRA PRADESH','VIZIANAGARAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (16,'ANDHRA PRADESH','WEST GODAVARI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (17,'ANDHRA PRADESH','Y.S.R.');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (18,'ARUNACHAL PRADESH','ANJAW');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (19,'ARUNACHAL PRADESH','CHANGLANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (20,'ARUNACHAL PRADESH','DIBANG VALLEY');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (21,'ARUNACHAL PRADESH','EAST KAMENG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (22,'ARUNACHAL PRADESH','EAST SIANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (23,'ARUNACHAL PRADESH','Kra Daadi');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (24,'ARUNACHAL PRADESH','KURUNG KUMEY');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (25,'ARUNACHAL PRADESH','LOHIT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (26,'ARUNACHAL PRADESH','LONGDING');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (27,'ARUNACHAL PRADESH','LOWER DIBANG VALLEY');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (28,'ARUNACHAL PRADESH','LOWER SUBANSIRI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (29,'ARUNACHAL PRADESH','NAMSAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (30,'ARUNACHAL PRADESH','PAPUM PARE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (31,'ARUNACHAL PRADESH','SIANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (32,'ARUNACHAL PRADESH','TAWANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (33,'ARUNACHAL PRADESH','TIRAP');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (34,'ARUNACHAL PRADESH','UPPER SIANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (35,'ARUNACHAL PRADESH','UPPER SUBANSIRI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (36,'ARUNACHAL PRADESH','WEST KAMENG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (37,'ARUNACHAL PRADESH','WEST SIANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (38,'ASSAM','BAKSA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (39,'ASSAM','BARPETA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (40,'ASSAM','BONGAIGAON');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (41,'ASSAM','CACHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (42,'ASSAM','CHIRANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (43,'ASSAM','DARRANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (44,'ASSAM','DHEMAJI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (45,'ASSAM','DHUBRI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (46,'ASSAM','DIBRUGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (47,'ASSAM','DIMA HASAO');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (48,'ASSAM','GOALPARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (49,'ASSAM','GOLAGHAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (50,'ASSAM','HAILAKANDI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (51,'ASSAM','JORHAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (52,'ASSAM','KAMRUP');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (53,'ASSAM','KAMRUP METRO');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (54,'ASSAM','KARBI ANGLONG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (55,'ASSAM','KARIMGANJ');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (56,'ASSAM','KOKRAJHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (57,'ASSAM','LAKHIMPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (58,'ASSAM','MARIGAON');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (59,'ASSAM','NAGAON');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (60,'ASSAM','NALBARI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (61,'ASSAM','SIVASAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (62,'ASSAM','SONITPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (63,'ASSAM','TINSUKIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (64,'ASSAM','UDALGURI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (65,'BIHAR','ARARIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (66,'BIHAR','ARWAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (67,'BIHAR','AURANGABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (68,'BIHAR','BANKA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (69,'BIHAR','BEGUSARAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (70,'BIHAR','BHAGALPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (71,'BIHAR','BHOJPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (72,'BIHAR','BUXAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (73,'BIHAR','DARBHANGA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (74,'BIHAR','GAYA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (75,'BIHAR','GOPALGANJ');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (76,'BIHAR','JAMUI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (77,'BIHAR','JEHANABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (78,'BIHAR','KAIMUR (BHABUA)');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (79,'BIHAR','KATIHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (80,'BIHAR','KHAGARIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (81,'BIHAR','KISHANGANJ');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (82,'BIHAR','LAKHISARAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (83,'BIHAR','MADHEPURA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (84,'BIHAR','MADHUBANI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (85,'BIHAR','MUNGER');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (86,'BIHAR','MUZAFFARPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (87,'BIHAR','NALANDA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (88,'BIHAR','NAWADA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (89,'BIHAR','PASHCHIM CHAMPARAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (90,'BIHAR','PATNA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (91,'BIHAR','PURBI CHAMPARAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (92,'BIHAR','PURNIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (93,'BIHAR','ROHTAS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (94,'BIHAR','SAHARSA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (95,'BIHAR','SAMASTIPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (96,'BIHAR','SARAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (97,'BIHAR','SHEIKHPURA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (98,'BIHAR','SHEOHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (99,'BIHAR','SITAMARHI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (100,'BIHAR','SIWAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (101,'BIHAR','SUPAUL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (102,'BIHAR','VAISHALI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (103,'CHANDIGARH','CHANDIGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (104,'CHHATTISGARH','BALOD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (105,'CHHATTISGARH','BALODA BAZAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (106,'CHHATTISGARH','BALRAMPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (107,'CHHATTISGARH','BASTAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (108,'CHHATTISGARH','BEMETARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (109,'CHHATTISGARH','BIJAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (110,'CHHATTISGARH','BILASPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (111,'CHHATTISGARH','DANTEWADA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (112,'CHHATTISGARH','DHAMTARI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (113,'CHHATTISGARH','DURG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (114,'CHHATTISGARH','GARIYABAND');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (115,'CHHATTISGARH','JANJGIR-CHAMPA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (116,'CHHATTISGARH','JASHPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (117,'CHHATTISGARH','KABIRDHAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (118,'CHHATTISGARH','KANKER');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (119,'CHHATTISGARH','KONDAGAON');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (120,'CHHATTISGARH','KORBA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (121,'CHHATTISGARH','KOREA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (122,'CHHATTISGARH','MAHASAMUND');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (123,'CHHATTISGARH','MUNGELI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (124,'CHHATTISGARH','NARAYANPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (125,'CHHATTISGARH','RAIGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (126,'CHHATTISGARH','RAIPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (127,'CHHATTISGARH','RAJNANDGAON');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (128,'CHHATTISGARH','SUKMA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (129,'CHHATTISGARH','SURAJPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (130,'CHHATTISGARH','SURGUJA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (131,'DADRA AND NAGAR HAVELI','DADRA AND NAGAR HAVELI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (132,'DAMAN AND DIU','DAMAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (133,'DAMAN AND DIU','DIU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (134,'DELHI','CENTRAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (135,'DELHI','EAST');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (136,'DELHI','NEW DELHI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (137,'DELHI','NORTH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (138,'DELHI','NORTH EAST');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (139,'DELHI','NORTH WEST');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (140,'DELHI','SHAHDARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (141,'DELHI','SOUTH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (142,'DELHI','South East');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (143,'DELHI','SOUTH WEST');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (144,'DELHI','WEST');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (145,'GOA','NORTH GOA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (146,'GOA','SOUTH GOA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (147,'GUJARAT','AHMADABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (148,'GUJARAT','AMRELI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (149,'GUJARAT','ANAND');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (150,'GUJARAT','ARVALLI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (151,'GUJARAT','BANAS KANTHA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (152,'GUJARAT','BHARUCH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (153,'GUJARAT','BHAVNAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (154,'GUJARAT','BOTAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (155,'GUJARAT','CHHOTAUDEPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (156,'GUJARAT','DANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (157,'GUJARAT','DEVBHUMI DWARKA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (158,'GUJARAT','DOHAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (159,'GUJARAT','GANDHINAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (160,'GUJARAT','GIR SOMNATH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (161,'GUJARAT','JAMNAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (162,'GUJARAT','JUNAGADH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (163,'GUJARAT','KACHCHH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (164,'GUJARAT','KHEDA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (165,'GUJARAT','MAHESANA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (166,'GUJARAT','Mahisagar');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (167,'GUJARAT','MORBI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (168,'GUJARAT','NARMADA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (169,'GUJARAT','NAVSARI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (170,'GUJARAT','PANCH MAHALS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (171,'GUJARAT','PATAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (172,'GUJARAT','PORBANDAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (173,'GUJARAT','RAJKOT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (174,'GUJARAT','SABAR KANTHA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (175,'GUJARAT','SURAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (176,'GUJARAT','SURENDRANAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (177,'GUJARAT','TAPI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (178,'GUJARAT','VADODARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (179,'GUJARAT','VALSAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (180,'HARYANA','AMBALA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (181,'HARYANA','BHIWANI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (182,'HARYANA','CHARKI DADRI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (183,'HARYANA','FARIDABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (184,'HARYANA','FATEHABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (185,'HARYANA','GURUGRAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (186,'HARYANA','HISAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (187,'HARYANA','JHAJJAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (188,'HARYANA','JIND');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (189,'HARYANA','KAITHAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (190,'HARYANA','KARNAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (191,'HARYANA','KURUKSHETRA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (192,'HARYANA','MAHENDRAGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (193,'HARYANA','MEWAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (194,'HARYANA','PALWAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (195,'HARYANA','PANCHKULA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (196,'HARYANA','PANIPAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (197,'HARYANA','REWARI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (198,'HARYANA','ROHTAK');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (199,'HARYANA','SIRSA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (200,'HARYANA','SONIPAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (201,'HARYANA','YAMUNANAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (202,'HIMACHAL PRADESH','BILASPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (203,'HIMACHAL PRADESH','CHAMBA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (204,'HIMACHAL PRADESH','HAMIRPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (205,'HIMACHAL PRADESH','KANGRA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (206,'HIMACHAL PRADESH','KINNAUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (207,'HIMACHAL PRADESH','KULLU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (208,'HIMACHAL PRADESH','LAHUL AND SPITI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (209,'HIMACHAL PRADESH','MANDI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (210,'HIMACHAL PRADESH','SHIMLA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (211,'HIMACHAL PRADESH','SIRMAUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (212,'HIMACHAL PRADESH','SOLAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (213,'HIMACHAL PRADESH','UNA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (214,'JAMMU AND KASHMIR','ANANTNAG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (215,'JAMMU AND KASHMIR','BADGAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (216,'JAMMU AND KASHMIR','BANDIPORA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (217,'JAMMU AND KASHMIR','BARAMULLA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (218,'JAMMU AND KASHMIR','DODA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (219,'JAMMU AND KASHMIR','GANDERBAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (220,'JAMMU AND KASHMIR','JAMMU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (221,'JAMMU AND KASHMIR','KARGIL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (222,'JAMMU AND KASHMIR','KATHUA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (223,'JAMMU AND KASHMIR','KISHTWAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (224,'JAMMU AND KASHMIR','KULGAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (225,'JAMMU AND KASHMIR','KUPWARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (226,'JAMMU AND KASHMIR','LEH LADAKH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (227,'JAMMU AND KASHMIR','POONCH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (228,'JAMMU AND KASHMIR','PULWAMA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (229,'JAMMU AND KASHMIR','RAJAURI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (230,'JAMMU AND KASHMIR','RAMBAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (231,'JAMMU AND KASHMIR','REASI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (232,'JAMMU AND KASHMIR','SAMBA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (233,'JAMMU AND KASHMIR','SHOPIAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (234,'JAMMU AND KASHMIR','SRINAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (235,'JAMMU AND KASHMIR','UDHAMPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (236,'JHARKHAND','BOKARO');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (237,'JHARKHAND','CHATRA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (238,'JHARKHAND','DEOGHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (239,'JHARKHAND','DHANBAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (240,'JHARKHAND','DUMKA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (241,'JHARKHAND','EAST SINGHBUM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (242,'JHARKHAND','GARHWA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (243,'JHARKHAND','GIRIDIH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (244,'JHARKHAND','GODDA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (245,'JHARKHAND','GUMLA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (246,'JHARKHAND','HAZARIBAGH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (247,'JHARKHAND','JAMTARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (248,'JHARKHAND','KHUNTI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (249,'JHARKHAND','KODERMA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (250,'JHARKHAND','LATEHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (251,'JHARKHAND','LOHARDAGA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (252,'JHARKHAND','PAKUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (253,'JHARKHAND','PALAMU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (254,'JHARKHAND','RAMGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (255,'JHARKHAND','RANCHI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (256,'JHARKHAND','SAHEBGANJ');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (257,'JHARKHAND','SARAIKELA KHARSAWAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (258,'JHARKHAND','SIMDEGA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (259,'JHARKHAND','WEST SINGHBHUM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (260,'KARNATAKA','BAGALKOT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (261,'KARNATAKA','BALLARI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (262,'KARNATAKA','BELAGAVI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (263,'KARNATAKA','BENGALURU RURAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (264,'KARNATAKA','BENGALURU URBAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (265,'KARNATAKA','BIDAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (266,'KARNATAKA','CHAMARAJANAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (267,'KARNATAKA','CHIKBALLAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (268,'KARNATAKA','CHIKKAMAGALURU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (269,'KARNATAKA','CHITRADURGA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (270,'KARNATAKA','DAKSHIN KANNAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (271,'KARNATAKA','DAVANGERE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (272,'KARNATAKA','DHARWAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (273,'KARNATAKA','GADAG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (274,'KARNATAKA','HASSAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (275,'KARNATAKA','HAVERI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (276,'KARNATAKA','KALABURAGI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (277,'KARNATAKA','KODAGU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (278,'KARNATAKA','KOLAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (279,'KARNATAKA','KOPPAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (280,'KARNATAKA','MANDYA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (281,'KARNATAKA','MYSURU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (282,'KARNATAKA','RAICHUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (283,'KARNATAKA','RAMANAGARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (284,'KARNATAKA','SHIVAMOGGA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (285,'KARNATAKA','TUMAKURU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (286,'KARNATAKA','UDUPI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (287,'KARNATAKA','UTTAR KANNAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (288,'KARNATAKA','VIJAYAPURA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (289,'KARNATAKA','YADGIR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (290,'KERALA','ALAPPUZHA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (291,'KERALA','ERNAKULAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (292,'KERALA','IDUKKI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (293,'KERALA','KANNUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (294,'KERALA','KASARAGOD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (295,'KERALA','KOLLAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (296,'KERALA','KOTTAYAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (297,'KERALA','KOZHIKODE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (298,'KERALA','MALAPPURAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (299,'KERALA','PALAKKAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (300,'KERALA','PATHANAMTHITTA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (301,'KERALA','THIRUVANANTHAPURAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (302,'KERALA','THRISSUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (303,'KERALA','WAYANAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (304,'LAKSHADWEEP','LAKSHADWEEP DISTRICT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (305,'MADHYA PRADESH','AGAR MALWA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (306,'MADHYA PRADESH','ALIRAJPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (307,'MADHYA PRADESH','ANUPPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (308,'MADHYA PRADESH','ASHOKNAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (309,'MADHYA PRADESH','BALAGHAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (310,'MADHYA PRADESH','BARWANI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (311,'MADHYA PRADESH','BETUL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (312,'MADHYA PRADESH','BHIND');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (313,'MADHYA PRADESH','BHOPAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (314,'MADHYA PRADESH','BURHANPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (315,'MADHYA PRADESH','CHHATARPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (316,'MADHYA PRADESH','CHHINDWARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (317,'MADHYA PRADESH','DAMOH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (318,'MADHYA PRADESH','DATIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (319,'MADHYA PRADESH','DEWAS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (320,'MADHYA PRADESH','DHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (321,'MADHYA PRADESH','DINDORI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (322,'MADHYA PRADESH','EAST NIMAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (323,'MADHYA PRADESH','GUNA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (324,'MADHYA PRADESH','GWALIOR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (325,'MADHYA PRADESH','HARDA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (326,'MADHYA PRADESH','HOSHANGABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (327,'MADHYA PRADESH','INDORE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (328,'MADHYA PRADESH','JABALPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (329,'MADHYA PRADESH','JHABUA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (330,'MADHYA PRADESH','KATNI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (331,'MADHYA PRADESH','KHARGONE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (332,'MADHYA PRADESH','MANDLA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (333,'MADHYA PRADESH','MANDSAUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (334,'MADHYA PRADESH','MORENA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (335,'MADHYA PRADESH','NARSINGHPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (336,'MADHYA PRADESH','NEEMUCH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (337,'MADHYA PRADESH','PANNA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (338,'MADHYA PRADESH','RAISEN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (339,'MADHYA PRADESH','RAJGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (340,'MADHYA PRADESH','RATLAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (341,'MADHYA PRADESH','REWA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (342,'MADHYA PRADESH','SAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (343,'MADHYA PRADESH','SATNA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (344,'MADHYA PRADESH','SEHORE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (345,'MADHYA PRADESH','SEONI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (346,'MADHYA PRADESH','SHAHDOL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (347,'MADHYA PRADESH','SHAJAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (348,'MADHYA PRADESH','SHEOPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (349,'MADHYA PRADESH','SHIVPURI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (350,'MADHYA PRADESH','SIDHI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (351,'MADHYA PRADESH','SINGRAULI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (352,'MADHYA PRADESH','TIKAMGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (353,'MADHYA PRADESH','UJJAIN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (354,'MADHYA PRADESH','UMARIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (355,'MADHYA PRADESH','VIDISHA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (356,'MAHARASHTRA','AHMEDNAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (357,'MAHARASHTRA','AKOLA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (358,'MAHARASHTRA','AMRAVATI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (359,'MAHARASHTRA','AURANGABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (360,'MAHARASHTRA','BEED');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (361,'MAHARASHTRA','BHANDARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (362,'MAHARASHTRA','BULDHANA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (363,'MAHARASHTRA','CHANDRAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (364,'MAHARASHTRA','DHULE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (365,'MAHARASHTRA','GADCHIROLI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (366,'MAHARASHTRA','GONDIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (367,'MAHARASHTRA','HINGOLI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (368,'MAHARASHTRA','JALGAON');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (369,'MAHARASHTRA','JALNA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (370,'MAHARASHTRA','KOLHAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (371,'MAHARASHTRA','LATUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (372,'MAHARASHTRA','MUMBAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (373,'MAHARASHTRA','MUMBAI SUBURBAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (374,'MAHARASHTRA','NAGPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (375,'MAHARASHTRA','NANDED');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (376,'MAHARASHTRA','NANDURBAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (377,'MAHARASHTRA','NASHIK');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (378,'MAHARASHTRA','OSMANABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (379,'MAHARASHTRA','PALGHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (380,'MAHARASHTRA','PARBHANI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (381,'MAHARASHTRA','PUNE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (382,'MAHARASHTRA','RAIGAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (383,'MAHARASHTRA','RATNAGIRI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (384,'MAHARASHTRA','SANGLI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (385,'MAHARASHTRA','SATARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (386,'MAHARASHTRA','SINDHUDURG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (387,'MAHARASHTRA','SOLAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (388,'MAHARASHTRA','THANE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (389,'MAHARASHTRA','WARDHA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (390,'MAHARASHTRA','WASHIM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (391,'MAHARASHTRA','YAVATMAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (392,'MANIPUR','BISHNUPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (393,'MANIPUR','CHANDEL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (394,'MANIPUR','CHURACHANDPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (395,'MANIPUR','IMPHAL EAST');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (396,'MANIPUR','IMPHAL WEST');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (397,'MANIPUR','SENAPATI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (398,'MANIPUR','TAMENGLONG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (399,'MANIPUR','THOUBAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (400,'MANIPUR','UKHRUL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (401,'MEGHALAYA','EAST GARO HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (402,'MEGHALAYA','EAST JAINTIA HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (403,'MEGHALAYA','EAST KHASI HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (404,'MEGHALAYA','NORTH GARO HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (405,'MEGHALAYA','RI BHOI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (406,'MEGHALAYA','SOUTH GARO HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (407,'MEGHALAYA','SOUTH WEST GARO HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (408,'MEGHALAYA','SOUTH WEST KHASI HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (409,'MEGHALAYA','WEST GARO HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (410,'MEGHALAYA','WEST JAINTIA HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (411,'MEGHALAYA','WEST KHASI HILLS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (412,'MIZORAM','AIZAWL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (413,'MIZORAM','CHAMPHAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (414,'MIZORAM','KOLASIB');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (415,'MIZORAM','LAWNGTLAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (416,'MIZORAM','LUNGLEI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (417,'MIZORAM','MAMIT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (418,'MIZORAM','SAIHA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (419,'MIZORAM','SERCHHIP');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (420,'NAGALAND','DIMAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (421,'NAGALAND','KIPHIRE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (422,'NAGALAND','KOHIMA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (423,'NAGALAND','LONGLENG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (424,'NAGALAND','MOKOKCHUNG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (425,'NAGALAND','MON');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (426,'NAGALAND','PEREN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (427,'NAGALAND','PHEK');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (428,'NAGALAND','TUENSANG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (429,'NAGALAND','WOKHA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (430,'NAGALAND','ZUNHEBOTO');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (431,'ODISHA','ANUGUL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (432,'ODISHA','BALANGIR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (433,'ODISHA','BALESHWAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (434,'ODISHA','BARGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (435,'ODISHA','BHADRAK');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (436,'ODISHA','BOUDH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (437,'ODISHA','CUTTACK');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (438,'ODISHA','DEOGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (439,'ODISHA','DHENKANAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (440,'ODISHA','GAJAPATI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (441,'ODISHA','GANJAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (442,'ODISHA','JAGATSINGHAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (443,'ODISHA','JAJAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (444,'ODISHA','JHARSUGUDA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (445,'ODISHA','KALAHANDI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (446,'ODISHA','KANDHAMAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (447,'ODISHA','KENDRAPARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (448,'ODISHA','KENDUJHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (449,'ODISHA','KHORDHA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (450,'ODISHA','KORAPUT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (451,'ODISHA','MALKANGIRI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (452,'ODISHA','MAYURBHANJ');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (453,'ODISHA','NABARANGPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (454,'ODISHA','NAYAGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (455,'ODISHA','NUAPADA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (456,'ODISHA','PURI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (457,'ODISHA','RAYAGADA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (458,'ODISHA','SAMBALPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (459,'ODISHA','SONEPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (460,'ODISHA','SUNDARGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (461,'PUDUCHERRY','KARAIKAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (462,'PUDUCHERRY','MAHE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (463,'PUDUCHERRY','PONDICHERRY');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (464,'PUDUCHERRY','YANAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (465,'PUNJAB','AMRITSAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (466,'PUNJAB','BARNALA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (467,'PUNJAB','BATHINDA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (468,'PUNJAB','FARIDKOT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (469,'PUNJAB','FATEHGARH SAHIB');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (470,'PUNJAB','FAZILKA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (471,'PUNJAB','FIROZEPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (472,'PUNJAB','GURDASPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (473,'PUNJAB','HOSHIARPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (474,'PUNJAB','JALANDHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (475,'PUNJAB','KAPURTHALA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (476,'PUNJAB','LUDHIANA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (477,'PUNJAB','MANSA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (478,'PUNJAB','MOGA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (479,'PUNJAB','NAWANSHAHR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (480,'PUNJAB','PATHANKOT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (481,'PUNJAB','PATIALA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (482,'PUNJAB','RUPNAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (483,'PUNJAB','SANGRUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (484,'PUNJAB','S.A.S Nagar');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (485,'PUNJAB','SRI MUKTSAR SAHIB');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (486,'PUNJAB','Tarn Taran');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (487,'RAJASTHAN','AJMER');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (488,'RAJASTHAN','ALWAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (489,'RAJASTHAN','BANSWARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (490,'RAJASTHAN','BARAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (491,'RAJASTHAN','BARMER');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (492,'RAJASTHAN','BHARATPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (493,'RAJASTHAN','BHILWARA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (494,'RAJASTHAN','BIKANER');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (495,'RAJASTHAN','BUNDI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (496,'RAJASTHAN','CHITTORGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (497,'RAJASTHAN','CHURU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (498,'RAJASTHAN','DAUSA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (499,'RAJASTHAN','DHOLPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (500,'RAJASTHAN','DUNGARPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (501,'RAJASTHAN','GANGANAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (502,'RAJASTHAN','HANUMANGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (503,'RAJASTHAN','JAIPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (504,'RAJASTHAN','JAISALMER');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (505,'RAJASTHAN','JALORE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (506,'RAJASTHAN','JHALAWAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (507,'RAJASTHAN','JHUNJHUNU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (508,'RAJASTHAN','JODHPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (509,'RAJASTHAN','KARAULI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (510,'RAJASTHAN','KOTA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (511,'RAJASTHAN','NAGAUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (512,'RAJASTHAN','PALI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (513,'RAJASTHAN','PRATAPGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (514,'RAJASTHAN','RAJSAMAND');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (515,'RAJASTHAN','SAWAI MADHOPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (516,'RAJASTHAN','SIKAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (517,'RAJASTHAN','SIROHI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (518,'RAJASTHAN','TONK');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (519,'RAJASTHAN','UDAIPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (520,'SIKKIM','EAST DISTRICT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (521,'SIKKIM','NORTH DISTRICT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (522,'SIKKIM','SOUTH DISTRICT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (523,'SIKKIM','WEST DISTRICT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (524,'TAMIL NADU','Ariyalur');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (525,'TAMIL NADU','CHENNAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (526,'TAMIL NADU','COIMBATORE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (527,'TAMIL NADU','CUDDALORE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (528,'TAMIL NADU','DHARMAPURI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (529,'TAMIL NADU','DINDIGUL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (530,'TAMIL NADU','ERODE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (531,'TAMIL NADU','KANCHIPURAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (532,'TAMIL NADU','KANNIYAKUMARI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (533,'TAMIL NADU','KARUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (534,'TAMIL NADU','KRISHNAGIRI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (535,'TAMIL NADU','MADURAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (536,'TAMIL NADU','NAGAPATTINAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (537,'TAMIL NADU','NAMAKKAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (538,'TAMIL NADU','PERAMBALUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (539,'TAMIL NADU','PUDUKKOTTAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (540,'TAMIL NADU','RAMANATHAPURAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (541,'TAMIL NADU','SALEM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (542,'TAMIL NADU','SIVAGANGA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (543,'TAMIL NADU','THANJAVUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (544,'TAMIL NADU','THENI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (545,'TAMIL NADU','THE NILGIRIS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (546,'TAMIL NADU','THIRUVALLUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (547,'TAMIL NADU','THIRUVARUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (548,'TAMIL NADU','TIRUCHIRAPPALLI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (549,'TAMIL NADU','TIRUNELVELI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (550,'TAMIL NADU','TIRUPPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (551,'TAMIL NADU','TIRUVANNAMALAI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (552,'TAMIL NADU','TUTICORIN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (553,'TAMIL NADU','VELLORE');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (554,'TAMIL NADU','VILLUPURAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (555,'TAMIL NADU','VIRUDHUNAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (556,'TELANGANA','ADILABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (557,'TELANGANA','BHADRADRI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (558,'TELANGANA','HYDERABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (559,'TELANGANA','Jagitial');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (560,'TELANGANA','JANGOAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (561,'TELANGANA','JAYASHANKAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (562,'TELANGANA','JOGULAMBA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (563,'TELANGANA','KAMAREDDY');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (564,'TELANGANA','KARIMNAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (565,'TELANGANA','KHAMMAM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (566,'TELANGANA','KOMARAM BHEEM ASIFABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (567,'TELANGANA','MAHABUBABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (568,'TELANGANA','MAHBUBNAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (569,'TELANGANA','MANCHERIAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (570,'TELANGANA','MEDAK');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (571,'TELANGANA','MEDCHAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (572,'TELANGANA','NAGARKURNOOL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (573,'TELANGANA','NALGONDA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (574,'TELANGANA','Nirmal');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (575,'TELANGANA','NIZAMABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (576,'TELANGANA','PEDDAPALLI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (577,'TELANGANA','RAJANNA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (578,'TELANGANA','RANGAREDDI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (579,'TELANGANA','SANGAREDDY');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (580,'TELANGANA','SIDDIPET');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (581,'TELANGANA','SURYAPET');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (582,'TELANGANA','VIKARABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (583,'TELANGANA','WANAPARTHY');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (584,'TELANGANA','WARANGAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (585,'TELANGANA','WARANGAL URBAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (586,'TELANGANA','YADADRI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (587,'TRIPURA','Dhalai');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (588,'TRIPURA','Gomati');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (589,'TRIPURA','Khowai');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (590,'TRIPURA','North Tripura');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (591,'TRIPURA','Sepahijala');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (592,'TRIPURA','South Tripura');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (593,'TRIPURA','Unakoti');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (594,'TRIPURA','West Tripura');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (595,'UTTARAKHAND','ALMORA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (596,'UTTARAKHAND','BAGESHWAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (597,'UTTARAKHAND','CHAMOLI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (598,'UTTARAKHAND','CHAMPAWAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (599,'UTTARAKHAND','DEHRADUN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (600,'UTTARAKHAND','HARIDWAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (601,'UTTARAKHAND','NAINITAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (602,'UTTARAKHAND','PAURI GARHWAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (603,'UTTARAKHAND','PITHORAGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (604,'UTTARAKHAND','RUDRA PRAYAG');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (605,'UTTARAKHAND','TEHRI GARHWAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (606,'UTTARAKHAND','UDAM SINGH NAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (607,'UTTARAKHAND','UTTAR KASHI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (608,'UTTAR PRADESH','AGRA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (609,'UTTAR PRADESH','ALIGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (610,'UTTAR PRADESH','ALLAHABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (611,'UTTAR PRADESH','AMBEDKAR NAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (612,'UTTAR PRADESH','Amethi');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (613,'UTTAR PRADESH','AMROHA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (614,'UTTAR PRADESH','AURAIYA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (615,'UTTAR PRADESH','AZAMGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (616,'UTTAR PRADESH','BAGHPAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (617,'UTTAR PRADESH','BAHRAICH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (618,'UTTAR PRADESH','BALLIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (619,'UTTAR PRADESH','BALRAMPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (620,'UTTAR PRADESH','BANDA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (621,'UTTAR PRADESH','BARABANKI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (622,'UTTAR PRADESH','BAREILLY');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (623,'UTTAR PRADESH','BASTI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (624,'UTTAR PRADESH','BHADOHI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (625,'UTTAR PRADESH','BIJNOR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (626,'UTTAR PRADESH','BUDAUN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (627,'UTTAR PRADESH','BULANDSHAHR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (628,'UTTAR PRADESH','CHANDAULI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (629,'UTTAR PRADESH','CHITRAKOOT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (630,'UTTAR PRADESH','DEORIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (631,'UTTAR PRADESH','ETAH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (632,'UTTAR PRADESH','ETAWAH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (633,'UTTAR PRADESH','FAIZABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (634,'UTTAR PRADESH','FARRUKHABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (635,'UTTAR PRADESH','FATEHPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (636,'UTTAR PRADESH','FIROZABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (637,'UTTAR PRADESH','GAUTAM BUDDHA NAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (638,'UTTAR PRADESH','GHAZIABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (639,'UTTAR PRADESH','GHAZIPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (640,'UTTAR PRADESH','GONDA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (641,'UTTAR PRADESH','GORAKHPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (642,'UTTAR PRADESH','HAMIRPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (643,'UTTAR PRADESH','HAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (644,'UTTAR PRADESH','HARDOI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (645,'UTTAR PRADESH','HATHRAS');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (646,'UTTAR PRADESH','JALAUN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (647,'UTTAR PRADESH','JAUNPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (648,'UTTAR PRADESH','JHANSI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (649,'UTTAR PRADESH','KANNAUJ');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (650,'UTTAR PRADESH','KANPUR DEHAT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (651,'UTTAR PRADESH','KANPUR NAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (652,'UTTAR PRADESH','Kasganj');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (653,'UTTAR PRADESH','KAUSHAMBI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (654,'UTTAR PRADESH','KHERI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (655,'UTTAR PRADESH','KUSHI NAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (656,'UTTAR PRADESH','LALITPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (657,'UTTAR PRADESH','LUCKNOW');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (658,'UTTAR PRADESH','MAHARAJGANJ');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (659,'UTTAR PRADESH','MAHOBA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (660,'UTTAR PRADESH','MAINPURI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (661,'UTTAR PRADESH','MATHURA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (662,'UTTAR PRADESH','MAU');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (663,'UTTAR PRADESH','MEERUT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (664,'UTTAR PRADESH','MIRZAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (665,'UTTAR PRADESH','MORADABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (666,'UTTAR PRADESH','MUZAFFARNAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (667,'UTTAR PRADESH','PILIBHIT');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (668,'UTTAR PRADESH','PRATAPGARH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (669,'UTTAR PRADESH','RAE BARELI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (670,'UTTAR PRADESH','RAMPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (671,'UTTAR PRADESH','SAHARANPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (672,'UTTAR PRADESH','SAMBHAL');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (673,'UTTAR PRADESH','SANT KABEER NAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (674,'UTTAR PRADESH','SHAHJAHANPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (675,'UTTAR PRADESH','SHAMLI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (676,'UTTAR PRADESH','SHRAVASTI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (677,'UTTAR PRADESH','SIDDHARTH NAGAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (678,'UTTAR PRADESH','SITAPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (679,'UTTAR PRADESH','SONBHADRA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (680,'UTTAR PRADESH','SULTANPUR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (681,'UTTAR PRADESH','UNNAO');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (682,'UTTAR PRADESH','VARANASI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (683,'WEST BENGAL','24 PARAGANAS NORTH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (684,'WEST BENGAL','24 PARAGANAS SOUTH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (685,'WEST BENGAL','Alipurduar');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (686,'WEST BENGAL','BANKURA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (687,'WEST BENGAL','BARDHAMAN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (688,'WEST BENGAL','BIRBHUM');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (689,'WEST BENGAL','COOCHBEHAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (690,'WEST BENGAL','DARJEELING');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (691,'WEST BENGAL','DINAJPUR DAKSHIN');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (692,'WEST BENGAL','DINAJPUR UTTAR');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (693,'WEST BENGAL','HOOGHLY');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (694,'WEST BENGAL','HOWRAH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (695,'WEST BENGAL','JALPAIGURI');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (696,'WEST BENGAL','KOLKATA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (697,'WEST BENGAL','MALDAH');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (698,'WEST BENGAL','MEDINIPUR EAST');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (699,'WEST BENGAL','MEDINIPUR WEST');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (700,'WEST BENGAL','MURSHIDABAD');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (701,'WEST BENGAL','NADIA');
INSERT INTO `india_state_district` (`id`,`state`,`district`) VALUES (702,'WEST BENGAL','PURULIA');
